### ISSUE TITLE
version 0.4.3.2 claims to work with ghc-8.2 but doesn't

### ISSUE THREAD

**Issue by bfrk** [jgm/zip-archive#68]
Compiling with ghc-8.2.2 results in a valid build plan but fails with this error.
```
[1 of 1] Compiling Codec.Archive.Zip ( src/Codec/Archive/Zip.hs, dist/build/Codec/Archive/Zip.o )

src/Codec/Archive/Zip.hs:809:26: error:
    • Variable not in scope: (<>) :: [Char] -> [Char] -> String
    • Perhaps you meant one of these:
        ‘<$>’ (imported from Control.Applicative),
        ‘<=’ (imported from Prelude), ‘</>’ (imported from System.FilePath)
    |
809 |                          <> "expected %d, got %d bytes")
```

Suggested solution: raise lower bound on base package.

**Comment by bfrk** [comment]
version 0.4.3.1 has the same problem, but not version 0.4.3

**Comment by jgm** [comment]
Alternatively we could import Data.Monoid.  But supporting ghc 8.2 doesn't seem important.
Do versions > 8.2 build correctly?

**Comment by bfrk** [comment]
Yes, later ghc versions are fine.

What you are going to do for future releases is up to you. I am personally fine with dropping support for ghc-8.2, it just means cabal will pick an earlier release, and those worked for us in the past. Importing Data.Monoid is also fine if it works.

The important part is that you fix the two broken releases on hackage: either deprecate them (but that seems a bit too drastic), or (preferably) add hackage revisions for them that raise the lower bound on base to > 4.10. Either one will solve our build problems by preventing cabal from choosing them with ghc-8.2 (or earlier).

**Comment by jgm** [comment]
I've published revisions for the last two releases.

**Comment by bfrk** [comment]
Thanks!
